Fix Plat/al export script after last upgrade
Since
https://github.com/Polytechnique-org/platal/commit/31933fafc2e7ed546f48fe2fafe360b5daf74662
the field profiles.xorg_id is a VARCHAR instead of an INT in the
database. So testing "== 0" no longer works, which makes importing
Plat/al data fail:

    django.core.exceptions.ValidationError: {'schoolid': [u'Un objet
    User account avec ce champ School ID existe d\xe9j\xe0.']}

Fix this by comparing with strings.