Make UnboundedCharField non-unique
When using UnboundedCharField(unique=True) with a MySQL database, the
MySQL server raises an error, which breaks manage.py migrate:

python manage.py migrate
Operations to perform:
  Apply all migrations: accounts, admin, auth, authgroupex, contenttypes, oidc_provider, sessions
Running migrations:
  Applying accounts.0001_initial...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
[...]
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'display'
used in key specification without a key length")

This happens with the following fields:

* Role.display: it does not need to be unique.
* User.schoolid: as this is short (10 digits now), use a bounded
  CharField instead. While at it, make User.axid unique too.
* AuthGroupeXClient.name: it does not need to be unique.

Fixes: https://github.com/Polytechnique-org/xorgauth/issues/53