Add tests for SetPasswordForm and PasswordChangeForm
These forms have been broken since commit ec35e8106575 ("Save a hashed
password for Google Apps") and fixed by commit 4d1a7b48b450 ("Add
missing validate method to GoogleAppsPasswordValidator"). In order to
prevent a future regression, use these forms in tests.

The new tests would have detected the bug by failing with the following
exception:

    AttributeError: 'GoogleAppsPasswordValidator' object has no
    attribute 'validate'

Closes: https://github.com/Polytechnique-org/xorgauth/issues/79